=== MythTV/mythtv/mythtv/themes/mythuitheme.dtd
<!-- Parameter entities to avoid repetition -->
<!ENTITY % common_attributes "name CDATA #REQUIRED
                              from CDATA #IMPLIED" >
<!ENTITY % widgets "(textarea|imagetype|statetype|button|buttonlist|buttontree|
                    textedit|checkbox|spinbox|progressbar|clock|webbrowser|
                    shape|guidegrid)" >
<!ENTITY % widget_common "(area|position|alpha|alphapulse|helptext|focusorder|
                           minsize|loadondemand)" >

<!-- MythUI Theme Root -->
<!ELEMENT mythuitheme (window|fontdef|%widgets;)*>

<!-- Font Definition -->
<!ELEMENT fontdef (pixelsize|size|color|shadowcolor|shadowoffset|shadowalpha|
                   outlinecolor|outlinesize|outlinealpha|italics|weight|bold|
                   letterspacing|wordspacing|decoration)*>
<!ATTLIST fontdef %common_attributes;
                  face CDATA #IMPLIED>
<!ELEMENT pixelsize  (#PCDATA)>
<!ELEMENT size  (#PCDATA)>
<!ELEMENT color  (#PCDATA)>
<!ELEMENT shadowcolor  (#PCDATA)>
<!ELEMENT shadowoffset  (#PCDATA)>
<!ELEMENT shadowalpha  (#PCDATA)>
<!ELEMENT outlinecolor  (#PCDATA)>
<!ELEMENT outlinesize  (#PCDATA)>
<!ELEMENT outlinealpha  (#PCDATA)>
<!ELEMENT italics  (#PCDATA)>
<!ELEMENT weight  (#PCDATA)>
<!ELEMENT letterspacing  (#PCDATA)>
<!ELEMENT wordspacing  (#PCDATA)>
<!ELEMENT decoration  (#PCDATA)>

<!-- Window/Screen -->
<!ELEMENT window (%widget_common;|fontdef|%widgets;)*>
<!ATTLIST window %common_attributes;>

<!-- Elements common to all widgets -->
<!ELEMENT area (#PCDATA)>
<!ELEMENT position (#PCDATA)>
<!ELEMENT alpha (#PCDATA)>
<!ELEMENT alphapulse EMPTY>
<!ATTLIST alphapulse min CDATA "0"
                     max CDATA "255"
                     change CDATA "5">
<!ELEMENT helptext (#PCDATA)>
<!ATTLIST helptext lang CDATA #IMPLIED>
<!ELEMENT focusorder (#PCDATA)>
<!ELEMENT minsize (#PCDATA)>
<!ELEMENT loadondemand (#PCDATA)>

<!-- Textarea Widget -->
<!ENTITY % textarea_elements "(case|font|cutdown|multiline|align|colorcycle|
                               scroll|value|template)">
<!ELEMENT textarea (%widget_common;|%textarea_elements;|%widgets;)*>
<!ATTLIST textarea %common_attributes;>
<!ELEMENT case (#PCDATA)>
<!ELEMENT font (#PCDATA)>
<!ATTLIST font state CDATA #IMPLIED>
<!ELEMENT cutdown (#PCDATA)>
<!ELEMENT multiline (#PCDATA)>
<!ELEMENT align (#PCDATA)>
<!ELEMENT colorcycle (#PCDATA)>
<!ATTLIST colorcycle start CDATA #IMPLIED
                     end CDATA #IMPLIED
                     steps CDATA #IMPLIED>
<!ELEMENT scroll (#PCDATA)> <!-- Not yet working -->
<!ATTLIST scroll direction (left|right|up|down) "left">
<!ELEMENT value (#PCDATA)>
<!ATTLIST value lang CDATA #IMPLIED>
<!ELEMENT template (#PCDATA)>
<!ATTLIST template type CDATA #IMPLIED>

<!-- Imagetype Widget -->
<!ELEMENT imagetype (%widget_common;|filename|alpha|preserveaspect|crop|
                     mask|reflection|grayscale|filepattern|delay|%widgets;)*>
<!ATTLIST imagetype %common_attributes;>
<!ELEMENT filename (#PCDATA)>
<!ELEMENT preserveaspect (#PCDATA)>
<!ELEMENT crop (#PCDATA)>
<!ELEMENT mask (#PCDATA)>
<!ELEMENT reflection EMPTY>
<!ATTLIST reflection axis CDATA "horizontal"
                     shear CDATA "0"
                     scale CDATA "100"
                     length CDATA "100"
                     spacing CDATA "0">
<!ELEMENT grayscale (#PCDATA)>
<!ELEMENT greyscale (#PCDATA)>
<!ELEMENT filepattern (#PCDATA)>
<!ATTLIST filepattern low CDATA "0"
                       high CDATA #REQUIRED
                       cycle (start|reverse) "start"
                       delay CDATA "500">
<!ELEMENT delay (#PCDATA)>  <!-- DEPRECATED -->

<!-- Shape Widget -->
<!ELEMENT shape (%widget_common;|type|cornerradius|fill|line|%widgets;)*>
<!ATTLIST shape %common_attributes;>
<!ELEMENT type (#PCDATA)>
<!ELEMENT fill (gradient*)>
<!ATTLIST fill color CDATA #IMPLIED
               alpha CDATA #IMPLIED
               style (solid|gradient) "solid">
<!ELEMENT gradient (stop*)>
<!ATTLIST gradient start CDATA #IMPLIED
                   end CDATA #IMPLIED
                   alpha CDATA #IMPLIED
                   direction (vertical|horizontal|diagonal) "vertical">
<!ELEMENT stop (#PCDATA)>
<!ATTLIST stop position CDATA #REQUIRED
               color CDATA #REQUIRED
               alpha CDATA #IMPLIED>
<!ELEMENT line (#PCDATA)>
<!ATTLIST line color CDATA "#000000"
               alpha CDATA "255"
               width CDATA "1"
               style (solid) "solid">
<!ELEMENT cornerradius (#PCDATA)>

<!-- Statetype Widget -->
<!ELEMENT statetype (%widget_common;|showempty|state|%widgets;)*>
<!ATTLIST statetype %common_attributes;>
<!ELEMENT showempty (#PCDATA)>
<!ELEMENT state (%widget_common;|fontdef|%widgets;)*>
<!ATTLIST state name CDATA #IMPLIED
                type CDATA #IMPLIED
                from CDATA #IMPLIED>

<!-- Clock Widget -->
<!ELEMENT clock (%widget_common;|%textarea_elements;|format|secondflash|
                 %widgets;)*>
<!ATTLIST clock %common_attributes;>
<!ELEMENT secondflash (#PCDATA)>

<!-- Button Widget -->
<!ELEMENT button (%widget_common;|value|%widgets;)*> <!-- statetype -->
<!ATTLIST button %common_attributes;>

<!-- Buttonlist Widget -->
<!ENTITY % buttonlist_elements "layout|spacing|arrange|align|scrollstyle|
                                wrapstyle|showarrow|buttonarea|drawfrombottom">
<!ELEMENT buttonlist (%widget_common;|%buttonlist_elements;|%widgets;)*> <!-- statetype -->
<!ATTLIST buttonlist %common_attributes;>
<!ELEMENT layout (#PCDATA)>
<!ELEMENT spacing (#PCDATA)>
<!ELEMENT arrange (#PCDATA)>
<!ELEMENT scrollstyle (#PCDATA)>
<!ELEMENT wrapstyle (#PCDATA)>
<!ELEMENT showarrow (#PCDATA)>
<!ELEMENT buttonarea (#PCDATA)>
<!ELEMENT drawfrombottom (#PCDATA)>

<!-- Buttontree Widget -->
<!ELEMENT buttontree (%widget_common;|numlists|spacing|%widgets;)*> <!-- buttonlist -->
<!ATTLIST buttontree %common_attributes;>
<!ELEMENT numlists  (#PCDATA)>

<!-- Textedit Widget -->
<!ELEMENT textedit (%widget_common;|%widgets;)*> <!-- textarea|statetype|imagetype -->
<!ATTLIST textedit %common_attributes;>
   
<!-- Checkbox Widget -->
<!ELEMENT checkbox (%widget_common;|%widgets;)*> <!-- statetype -->
<!ATTLIST checkbox %common_attributes;>

<!-- Spinbox Widget -->
<!ELEMENT spinbox (%widget_common;|%buttonlist_elements;|template|%widgets;)*> <!-- statetype -->
<!ATTLIST spinbox %common_attributes;>

<!-- Progressbar Widget -->
<!ELEMENT progressbar (%widget_common;|layout|style|%widgets;)*> <!-- imagetype -->
<!ATTLIST progressbar %common_attributes;>
<!ELEMENT style (#PCDATA)>

<!-- Guidegrid Widget -->
<!ELEMENT guidegrid (%widget_common;|layout|channels|timeslots|solidcolor|
                     selector|showcategories|categoryalpha|recordingcolor|
                     conflictingcolor|cutdown|multiline|textoffset|recordstatus|
                     arrow|font|%widgets;)*>
<!ATTLIST guidegrid %common_attributes;>
<!ELEMENT channels  (#PCDATA)>
<!ELEMENT timeslots  (#PCDATA)>
<!ELEMENT solidcolor  (#PCDATA)>
<!ELEMENT selector EMPTY>
<!ATTLIST selector type (highlight|box|roundbox) #IMPLIED
                   linecolor CDATA #IMPLIED
                   fillcolor CDATA #IMPLIED>
<!ELEMENT showcategories  (#PCDATA)>
<!ELEMENT categoryalpha  (#PCDATA)>
<!ELEMENT recordingcolor  (#PCDATA)>
<!ELEMENT conflictingcolor  (#PCDATA)>
<!ELEMENT textoffset  (#PCDATA)>
<!ELEMENT recordstatus EMPTY>
<!ATTLIST recordstatus type (SingleRecord|TimeslotRecord|ChannelRecord|
                             AllRecord|WeekslotRecord|FindOneRecord|
                             OverrideRecord) #REQUIRED
                       image CDATA #REQUIRED>
<!ELEMENT arrow EMPTY>
<!ATTLIST arrow direction (left|right) #REQUIRED
                image CDATA #REQUIRED>

<!-- Webbrowser Widget -->
<!ELEMENT webbrowser (%widget_common;|url|zoom|background|userstylesheet|
                      updateinterval|%widgets;)*>
<!ATTLIST webbrowser %common_attributes;>
<!ELEMENT url (#PCDATA)>
<!ELEMENT zoom (#PCDATA)>
<!ELEMENT background (#PCDATA)>
<!ATTLIST background color CDATA #REQUIRED
                     alpha CDATA #IMPLIED>
<!ELEMENT userstylesheet (#PCDATA)> 
<!ELEMENT updateinterval (#PCDATA)>

=== MythTV/mythtv/mythtv/themes/default/osd_subtitle.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE mythuitheme SYSTEM "http://www.mythtv.org/schema/mythuitheme.dtd">
<mythuitheme>
    <window name="osd_subtitle">
        <!--
            This is a reference implementation of the system/provider
            defaults specified in
            SubtitleFormat:CreateProviderDefault().

            Note that if all attributes/elements are simply inherited
            from provider, then the specification is optional.  E.g.,
            the following could be omitted:

            <fontdef name="sample" from="provider"></fontdef>
            <shape   name="sample" from="provider"></shape>

            Also note that these specific definitions are unnecessary
            since they are the same as the defaults in the code.  A
            theme only needs to include the definitions that it wants
            to change/override.
          -->

        <!--
	    Define a black background which is used below for 608 and
	    text subtitles.  If a background is not used, it is
	    recommended to use a 2-pixel outline or shadow in the
	    fontdef, in order to provide sufficient contrast.  Note
	    that 708 captions providers almost always specify an
	    explicit black background.
	  -->
        <shape name="black_background" from="provider">
          <type>box</type>
          <fill color="#000000" alpha="255" />
        </shape>


        <!--
            Subtitle type "text" generally comes from external text
            files like .srt or .txt files.
           -->
        <fontdef name="text" face="Droid Sans" from="provider">
        </fontdef>

        <shape   name="text" from="black_background">
        </shape>


        <!--
            Digital teletext text-based subtitles.  Not to be confused
            with bitmap teletext subtitles, or CEA-608 teletext
            captions.  A monospaced font should be used.
           -->
        <fontdef name="teletext" face="FreeMono" from="provider">
        </fontdef>


        <!--
            CEA-608 closed captions.  These also apply to CEA-608 VBI
            teletext captions.  A monospaced font should be used.
           -->
        <fontdef name="608" face="FreeMono" from="provider">
        </fontdef>

        <shape   name="608" from="black_background">
        </shape>


        <!--
            CEA-708 closed captions.  The spec defines 8 different
            font tags, but in practice (at least in the U.S.), only
            tags 0 and 3 are used by broadcasters.
           -->
        <!-- Font tag 0: "Default" -->
        <fontdef name="708_0" face="FreeMono"        from="provider">
        </fontdef>

        <!-- Font tag 1: "Monospaced Serif" -->
        <fontdef name="708_1" face="FreeMono"        from="provider">
        </fontdef>

        <!-- Font tag 2: "Proportional Serif" -->
        <fontdef name="708_2" face="Droid Serif"     from="provider">
        </fontdef>

        <!-- Font tag 3: "Monospaced Sans Serif" -->
        <fontdef name="708_3" face="Droid Sans Mono" from="provider">
        </fontdef>

        <!-- Font tag 4: "Proportional Sans Serif" -->
        <fontdef name="708_4" face="Droid Sans"      from="provider">
        </fontdef>

        <!-- Font tag 5: "Casual" -->
        <fontdef name="708_5" face="Purisa"          from="provider">
        </fontdef>

        <!-- Font tag 6: "Cursive" -->
        <fontdef name="708_6" face="TeX Gyre Chorus" from="provider">
        </fontdef>

        <!-- Font tag 7: "Small Capitals" -->
	<!-- Note: The Qt property QFont::SmallCaps is automatically
	     applied to this font. -->
        <fontdef name="708_7" face="Droid Serif"     from="provider">
        </fontdef>

    </window>
</mythuitheme>

=== MythTV/mythtv/mythtv/themes/MythCenter-wide/controls-ui.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE mythuitheme SYSTEM "http://www.mythtv.org/schema/mythuitheme.dtd">
<mythuitheme>

    <window name="keygrabpopup">
        <area>390,150,500,500</area>
        <shape name="backimg" from="basepopupbackground">
            <area>0,0,100%,100%</area>
        </shape>

        <textarea name="message" from="basetextarea">
            <area>18,18,460,400</area>
            <multiline>yes</multiline>
        </textarea>

        <button name="cancel" from="basebutton">
            <position>84,420</position>
            <value>Cancel</value>
        </button>

        <button name="ok" from="basebutton">
            <position>264,420</position>
            <value>OK</value>
        </button>
    </window>

    <window name="controls">

        <textarea name="leftdesc" from="basetextarea">
            <area>64,46,560,30</area>
            <value>Contexts</value>
            <align>center</align>
        </textarea>

        <buttonlist name="leftlist" from="basebuttonlist">
            <area>64,86,560,440</area>
            <showarrow>no</showarrow>
        </buttonlist>

        <textarea name="rightdesc" from="leftdesc">
            <area>656,46,560,30</area>
            <value>Actions</value>
        </textarea>

        <buttonlist name="rightlist" from="leftlist">
            <area>656,86,560,440</area>
        </buttonlist>

        <button name="action_0" from="basebutton">
            <position>274,560</position>
        </button>

        <button name="action_1" from="action_0">
            <position>464,560</position>
        </button>

        <button name="action_2" from="action_0">
            <position>654,560</position>
        </button>

        <button name="action_3" from="action_0">
            <position>844,560</position>
        </button>

        <textarea name="description" from="basetextarea">
            <area>64,600,1152,90</area>
            <multiline>yes</multiline>
            <align>center</align>
        </textarea>

    </window>
</mythuitheme>

=== MythTV/mythtv/mythtv/themes/default-wide/appear-ui.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE mythuitheme SYSTEM "http://www.mythtv.org/schema/mythuitheme.dtd">
<mythuitheme>
    <window name="appearance">

        <fontdef name="title" face="DejaVu Sans">
            <color>#ffffff</color>
            <size>18</size>
            <weight>bold</weight>
        </fontdef>

        <shape name="blackout">
            <type>box</type>
            <fill style="solid" color="black"></fill>
        </shape>

        <imagetype name="preview">
            <filename>preview.png</filename>
            <preserveaspect>FALSE</preserveaspect>
        </imagetype>

        <textarea name="part">
            <font>title</font>
            <area>20,20,800,40</area>
            <value>Appearance Wizard</value>
            <align>center</align>
        </textarea>

        <textarea name="part1">
            <font>title</font>
            <area>100,140,600,170</area>
            <value>Move the selected corner of the preview image to the corner of the TV screen.  Press SELECT to edit the other corner.  Press MENU for options and ESC to quit.</value>
            <multiline>yes</multiline>
        </textarea>

        <textarea name="size">
            <font>title</font>
            <area>100,270,500,50</area>
        </textarea>

        <textarea name="offsets">
            <font>title</font>
            <area>100,320,500,140</area>
        </textarea>

        <textarea name="changeamount">
            <font>title</font>
            <area>100,520,500,140</area>
        </textarea>

    </window>
</mythuitheme>
