=== MythTV/mythtv/mythtv/themes/mythuitheme.dtd
<!-- Parameter entities to avoid repetition -->
<!ENTITY % common_attributes "name CDATA #REQUIRED
                              from CDATA #IMPLIED" >
<!ENTITY % widgets "(textarea|imagetype|statetype|button|buttonlist|buttontree|
                    textedit|checkbox|spinbox|progressbar|clock|webbrowser|
                    shape|guidegrid)" >
<!ENTITY % widget_common "(area|position|alpha|alphapulse|helptext|focusorder|
                           minsize|loadondemand)" >

<!-- MythUI Theme Root -->
<!ELEMENT mythuitheme (window|fontdef|%widgets;)*>

<!-- Font Definition -->
<!ELEMENT fontdef (pixelsize|size|color|shadowcolor|shadowoffset|shadowalpha|
                   outlinecolor|outlinesize|outlinealpha|italics|weight|bold|
                   letterspacing|wordspacing|decoration)*>
<!ATTLIST fontdef %common_attributes;
                  face CDATA #IMPLIED>
<!ELEMENT pixelsize  (#PCDATA)>
<!ELEMENT size  (#PCDATA)>
<!ELEMENT color  (#PCDATA)>
<!ELEMENT shadowcolor  (#PCDATA)>
<!ELEMENT shadowoffset  (#PCDATA)>
<!ELEMENT shadowalpha  (#PCDATA)>
<!ELEMENT outlinecolor  (#PCDATA)>
<!ELEMENT outlinesize  (#PCDATA)>
<!ELEMENT outlinealpha  (#PCDATA)>
<!ELEMENT italics  (#PCDATA)>
<!ELEMENT weight  (#PCDATA)>
<!ELEMENT letterspacing  (#PCDATA)>
<!ELEMENT wordspacing  (#PCDATA)>
<!ELEMENT decoration  (#PCDATA)>

<!-- Window/Screen -->
<!ELEMENT window (%widget_common;|fontdef|%widgets;)*>
<!ATTLIST window %common_attributes;>

<!-- Elements common to all widgets -->
<!ELEMENT area (#PCDATA)>
<!ELEMENT position (#PCDATA)>
<!ELEMENT alpha (#PCDATA)>
<!ELEMENT alphapulse EMPTY>
<!ATTLIST alphapulse min CDATA "0"
                     max CDATA "255"
                     change CDATA "5">
<!ELEMENT helptext (#PCDATA)>
<!ATTLIST helptext lang CDATA #IMPLIED>
<!ELEMENT focusorder (#PCDATA)>
<!ELEMENT minsize (#PCDATA)>
<!ELEMENT loadondemand (#PCDATA)>

<!-- Textarea Widget -->
<!ENTITY % textarea_elements "(case|font|cutdown|multiline|align|colorcycle|
                               scroll|value|template)">
<!ELEMENT textarea (%widget_common;|%textarea_elements;|%widgets;)*>
<!ATTLIST textarea %common_attributes;>
<!ELEMENT case (#PCDATA)>
<!ELEMENT font (#PCDATA)>
<!ATTLIST font state CDATA #IMPLIED>
<!ELEMENT cutdown (#PCDATA)>
<!ELEMENT multiline (#PCDATA)>
<!ELEMENT align (#PCDATA)>
<!ELEMENT colorcycle (#PCDATA)>
<!ATTLIST colorcycle start CDATA #IMPLIED
                     end CDATA #IMPLIED
                     steps CDATA #IMPLIED>
<!ELEMENT scroll (#PCDATA)> <!-- Not yet working -->
<!ATTLIST scroll direction (left|right|up|down) "left">
<!ELEMENT value (#PCDATA)>
<!ATTLIST value lang CDATA #IMPLIED>
<!ELEMENT template (#PCDATA)>
<!ATTLIST template type CDATA #IMPLIED>

<!-- Imagetype Widget -->
<!ELEMENT imagetype (%widget_common;|filename|alpha|preserveaspect|crop|
                     mask|reflection|grayscale|filepattern|delay|%widgets;)*>
<!ATTLIST imagetype %common_attributes;>
<!ELEMENT filename (#PCDATA)>
<!ELEMENT preserveaspect (#PCDATA)>
<!ELEMENT crop (#PCDATA)>
<!ELEMENT mask (#PCDATA)>
<!ELEMENT reflection EMPTY>
<!ATTLIST reflection axis CDATA "horizontal"
                     shear CDATA "0"
                     scale CDATA "100"
                     length CDATA "100"
                     spacing CDATA "0">
<!ELEMENT grayscale (#PCDATA)>
<!ELEMENT greyscale (#PCDATA)>
<!ELEMENT filepattern (#PCDATA)>
<!ATTLIST filepattern low CDATA "0"
                       high CDATA #REQUIRED
                       cycle (start|reverse) "start"
                       delay CDATA "500">
<!ELEMENT delay (#PCDATA)>  <!-- DEPRECATED -->

<!-- Shape Widget -->
<!ELEMENT shape (%widget_common;|type|cornerradius|fill|line|%widgets;)*>
<!ATTLIST shape %common_attributes;>
<!ELEMENT type (#PCDATA)>
<!ELEMENT fill (gradient*)>
<!ATTLIST fill color CDATA #IMPLIED
               alpha CDATA #IMPLIED
               style (solid|gradient) "solid">
<!ELEMENT gradient (stop*)>
<!ATTLIST gradient start CDATA #IMPLIED
                   end CDATA #IMPLIED
                   alpha CDATA #IMPLIED
                   direction (vertical|horizontal|diagonal) "vertical">
<!ELEMENT stop (#PCDATA)>
<!ATTLIST stop position CDATA #REQUIRED
               color CDATA #REQUIRED
               alpha CDATA #IMPLIED>
<!ELEMENT line (#PCDATA)>
<!ATTLIST line color CDATA "#000000"
               alpha CDATA "255"
               width CDATA "1"
               style (solid) "solid">
<!ELEMENT cornerradius (#PCDATA)>

<!-- Statetype Widget -->
<!ELEMENT statetype (%widget_common;|showempty|state|%widgets;)*>
<!ATTLIST statetype %common_attributes;>
<!ELEMENT showempty (#PCDATA)>
<!ELEMENT state (%widget_common;|fontdef|%widgets;)*>
<!ATTLIST state name CDATA #IMPLIED
                type CDATA #IMPLIED
                from CDATA #IMPLIED>

<!-- Clock Widget -->
<!ELEMENT clock (%widget_common;|%textarea_elements;|format|secondflash|
                 %widgets;)*>
<!ATTLIST clock %common_attributes;>
<!ELEMENT secondflash (#PCDATA)>

<!-- Button Widget -->
<!ELEMENT button (%widget_common;|value|%widgets;)*> <!-- statetype -->
<!ATTLIST button %common_attributes;>

<!-- Buttonlist Widget -->
<!ENTITY % buttonlist_elements "layout|spacing|arrange|align|scrollstyle|
                                wrapstyle|showarrow|buttonarea|drawfrombottom">
<!ELEMENT buttonlist (%widget_common;|%buttonlist_elements;|%widgets;)*> <!-- statetype -->
<!ATTLIST buttonlist %common_attributes;>
<!ELEMENT layout (#PCDATA)>
<!ELEMENT spacing (#PCDATA)>
<!ELEMENT arrange (#PCDATA)>
<!ELEMENT scrollstyle (#PCDATA)>
<!ELEMENT wrapstyle (#PCDATA)>
<!ELEMENT showarrow (#PCDATA)>
<!ELEMENT buttonarea (#PCDATA)>
<!ELEMENT drawfrombottom (#PCDATA)>

<!-- Buttontree Widget -->
<!ELEMENT buttontree (%widget_common;|numlists|spacing|%widgets;)*> <!-- buttonlist -->
<!ATTLIST buttontree %common_attributes;>
<!ELEMENT numlists  (#PCDATA)>

<!-- Textedit Widget -->
<!ELEMENT textedit (%widget_common;|%widgets;)*> <!-- textarea|statetype|imagetype -->
<!ATTLIST textedit %common_attributes;>
   
<!-- Checkbox Widget -->
<!ELEMENT checkbox (%widget_common;|%widgets;)*> <!-- statetype -->
<!ATTLIST checkbox %common_attributes;>

<!-- Spinbox Widget -->
<!ELEMENT spinbox (%widget_common;|%buttonlist_elements;|template|%widgets;)*> <!-- statetype -->
<!ATTLIST spinbox %common_attributes;>

<!-- Progressbar Widget -->
<!ELEMENT progressbar (%widget_common;|layout|style|%widgets;)*> <!-- imagetype -->
<!ATTLIST progressbar %common_attributes;>
<!ELEMENT style (#PCDATA)>

<!-- Guidegrid Widget -->
<!ELEMENT guidegrid (%widget_common;|layout|channels|timeslots|solidcolor|
                     selector|showcategories|categoryalpha|recordingcolor|
                     conflictingcolor|cutdown|multiline|textoffset|recordstatus|
                     arrow|font|%widgets;)*>
<!ATTLIST guidegrid %common_attributes;>
<!ELEMENT channels  (#PCDATA)>
<!ELEMENT timeslots  (#PCDATA)>
<!ELEMENT solidcolor  (#PCDATA)>
<!ELEMENT selector EMPTY>
<!ATTLIST selector type (highlight|box|roundbox) #IMPLIED
                   linecolor CDATA #IMPLIED
                   fillcolor CDATA #IMPLIED>
<!ELEMENT showcategories  (#PCDATA)>
<!ELEMENT categoryalpha  (#PCDATA)>
<!ELEMENT recordingcolor  (#PCDATA)>
<!ELEMENT conflictingcolor  (#PCDATA)>
<!ELEMENT textoffset  (#PCDATA)>
<!ELEMENT recordstatus EMPTY>
<!ATTLIST recordstatus type (SingleRecord|TimeslotRecord|ChannelRecord|
                             AllRecord|WeekslotRecord|FindOneRecord|
                             OverrideRecord) #REQUIRED
                       image CDATA #REQUIRED>
<!ELEMENT arrow EMPTY>
<!ATTLIST arrow direction (left|right) #REQUIRED
                image CDATA #REQUIRED>

<!-- Webbrowser Widget -->
<!ELEMENT webbrowser (%widget_common;|url|zoom|background|userstylesheet|
                      updateinterval|%widgets;)*>
<!ATTLIST webbrowser %common_attributes;>
<!ELEMENT url (#PCDATA)>
<!ELEMENT zoom (#PCDATA)>
<!ELEMENT background (#PCDATA)>
<!ATTLIST background color CDATA #REQUIRED
                     alpha CDATA #IMPLIED>
<!ELEMENT userstylesheet (#PCDATA)> 
<!ELEMENT updateinterval (#PCDATA)>

=== MythTV/mythtv/mythtv/themes/MythCenter-wide/appear-ui.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE mythuitheme SYSTEM "http://www.mythtv.org/schema/mythuitheme.dtd">
<mythuitheme>
    <window name="appearance">
        <textarea name="part">
            <font>baselarge</font>
            <area>20,20,800,40</area>
            <value>Appearance Wizard</value>
            <align>center</align>
        </textarea>

        <shape name="blackout">
            <type>box</type>
            <fill style="solid" color="black"></fill>
        </shape>

        <imagetype name="preview">
            <filename>preview.png</filename>
            <preserveaspect>FALSE</preserveaspect>
        </imagetype>

        <textarea name="part1">
            <font>baselarge</font>
            <area>100,140,600,170</area>
            <value>Move the selected corner of the preview image to the corner of the TV screen.  Press SELECT to edit the other corner.  Press MENU for options and ESC to quit.</value>
            <multiline>yes</multiline>
        </textarea>

        <textarea name="size">
            <font>baselarge</font>
            <area>100,270,500,50</area>
        </textarea>

        <textarea name="offsets">
            <font>baselarge</font>
            <area>100,320,500,140</area>
        </textarea>

        <textarea name="changeamount">
            <font>baselarge</font>
            <area>100,520,500,140</area>
        </textarea>

    </window>
</mythuitheme>

=== MythTV/mythtv/mythplugins/mythgallery/theme/default/gallery-ui.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE mythuitheme SYSTEM "http://www.mythtv.org/schema/mythuitheme.dtd">
<mythuitheme>

    <window name="gallery">

        <!-- optional - shows current image name -->
        <textarea name="title" from="basetextarea">
            <area>15,20,500,50</area>
            <cutdown>yes</cutdown>
            <font>baselarge</font>
        </textarea>

        <!-- optional - shows path to current image -->
<!--    <textarea name="breadcrumbs" from="basetextarea">
            <area>70,15,460,30</area>
            <font>basemedium</font>
            <align>left,vcenter</align>
        </textarea>
-->
        <buttonlist name="images">
            <area>15,0,770,585</area>
            <layout>grid</layout>
            <spacing>5</spacing>
            <buttonarea>0,65,770,520</buttonarea>
            <statetype name="buttonitem">
                <area>0,0,150,125</area>
                <state name="active">
                    <imagetype name="buttonbackground">
                        <filename>shared/grid_back_reg.png</filename>
                    </imagetype>
                    <imagetype name="buttonimage">
                        <area>10,8,130,90</area>
                        <preserveaspect>true</preserveaspect>
                        <filename>shared/grid_noimage.png</filename>
                    </imagetype>
                    <statetype name="nodetype">
                        <position>80,55</position>
                        <state name="subfolder">
                            <imagetype name="icon">
                                <area>0,0,50,50</area>
                                <filename>shared/directory.png</filename>
                                <preserveaspect>yes</preserveaspect>
                            </imagetype>
                        </state>
                        <state name="upfolder">
                            <imagetype name="icon">
                                <area>0,0,50,50</area>
                                <filename>shared/updirectory.png</filename>
                                <preserveaspect>yes</preserveaspect>
                            </imagetype>
                        </state>
                    </statetype>
                    <textarea name="buttontext">
                        <area>5,98,140,25</area>
                        <font>menufont</font>
                        <align>hcenter,bottom</align>
                    </textarea>
                    <textarea name="childcount" from="basetextarea">
                        <area>65,72,55,20</area>
                        <font>basesmallblack</font>
                        <align>right</align>
                    </textarea>
                    <statetype name="buttoncheck">
                        <position>130,105</position>
                        <showempty>yes</showempty>
                        <state type="full">
                            <imagetype name="marked">
                                <filename>gallery-mark.png</filename>
                            </imagetype>
                        </state>
                    </statetype>
                </state>
                <state name="selectedactive" from="active">
                    <imagetype name="buttonbackground">
                        <filename>shared/grid_back_sel.png</filename>
                    </imagetype>
                </state>
            </statetype>
            <statetype name="upscrollarrow">
                <position>640,20</position>
                <showempty>yes</showempty>
                <state type="full">
                    <imagetype name="upon">
                        <filename>up_arrow.png</filename>
                    </imagetype>
                </state>
            </statetype>
            <statetype name="downscrollarrow">
                <position>700,20</position>
                <showempty>yes</showempty>
                <state type="full">
                    <imagetype name="dnon">
                        <filename>down_arrow.png</filename>
                    </imagetype>
                </state>
            </statetype>
        </buttonlist>

        <textarea name="position" from="basetextarea">
            <area>530,15,110,40</area>
            <align>hcenter,vcenter</align>
            <font>basemedium</font>
        </textarea>

        <!-- optional - shows a message when no images are available
             in the current directory -->
        <textarea name="noimages" from="basetextarea">
            <area>15,20,770,560</area>
            <font>basemedium</font>
            <align>allcenter</align>
        </textarea>
    </window>

    <window name="filter">

        <textarea name="title" from="basetextarea">
            <area>20,50,770,30</area>
            <value>Filter/sort images</value>
            <align>hcenter,vcenter</align>
            <font>baselarge</font>
        </textarea>

        <!-- Filter: labels -->
        <textarea name="filter_text" from="basetextarea">
            <area>10,107,180,34</area>
            <value>Directory filter :</value>
            <align>right,top</align>
        </textarea>

        <textarea name="type_filter" from="filter_text">
            <position>10,161</position>
            <value>Type filter :</value>
        </textarea>

        <textarea name="numimages_text" from="basetextarea">
            <area>200,255,770,30</area>
            <value>NumImages_Text</value>
            <align>left,top</align>
        </textarea>

        <!-- Sort: labels -->
        <textarea name="sort_text" from="basetextarea">
            <area>10,319,180,34</area>
            <value>Sort by :</value>
            <align>right,top</align>
        </textarea>

        <!-- Widgets -->
        <textedit name="dirfilter_text" from="basetextedit">
            <position>200,100</position>
        </textedit>

        <buttonlist name="typefilter_select" from="baseselector">
            <position>200,154</position>
        </buttonlist>

        <button name="check_button" from="basebutton">
            <position>200,200</position>
            <value>Check Filter</value>
        </button>

        <buttonlist name="sort_select" from="baseselector">
            <position>200,312</position>
        </buttonlist>

        <button name="done_button" from="basebutton">
            <position>380,505</position>
            <value>Done</value>
        </button>

        <button name="save_button" from="basebutton">
            <position>200,505</position>
            <value>Save as default</value>
        </button>

    </window>
</mythuitheme>

=== MythTV/mythtv/mythtv/themes/Terra/welcome-ui.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE mythuitheme SYSTEM "../mythuitheme.dtd">
<mythuitheme>

    <window name="welcome_screen">

        <imagetype name="backdrop" from="basebackdrop" />
        <imagetype name="topbar" from="basetopbar" />

        <textarea name="title" from="baseheading">
            <value>Welcome to MythTV</value>
        </textarea>	

        <!--
            current myth status
        -->
        <textarea name="status_text" from="basetextarea">
            <area>32,64,1216,72</area>
            <multiline>yes</multiline>
            <font>basemedium</font>
            <align>hcenter</align>
            <value>MythTV is idle and will shutdown shortly.</value>
        </textarea>

        <!--
            current recordings status
        -->
        <textarea name="recording_label" from="basetextarea">
            <area>32,136,1216,36</area>
            <font>baseextralarge</font>
            <align>hcenter</align>
            <value>Current Recording(s)</value>
        </textarea>

        <textarea name="recording_text" from="status_text">
            <area>32,178,1216,180</area>
            <value>Retrieving Recording Status...</value>
        </textarea>

        <!--
            next scheduled recording status
        -->
        <textarea name="scheduled_label" from="recording_label">
            <area>32,364,1216,36</area>
            <value>Next Scheduled Recording(s)</value>
        </textarea>

        <textarea name="scheduled_text" from="recording_text">
            <area>32,406,1216,144</area>
            <value>Retrieving Scheduled Recordings...</value>
        </textarea>

        <!--
            scheduled recordings conflict warning
        -->
        <textarea name="conflicts_text" from="basetextarea">
            <area>32,568,1216,36</area>
            <font>basesmallyellow</font>
            <align>hcenter</align>
            <value>WARNING: There are conflicting scheduled recordings!</value>
        </textarea>

        <!--
            start frontend button
        -->
        <button name="startfrontend_button" from="basewidebutton">
            <position>457,615</position>
            <value>Start Frontend</value>
        </button>

    </window>
</mythuitheme>

=== MythTV/mythtv/mythtv/themes/default/image-ui.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE mythuitheme SYSTEM "http://www.mythtv.org/schema/mythuitheme.dtd">
<mythuitheme>

    <window name="gallery">

        <!--shows path to current image -->
        <textarea name="breadcrumbs" from="basetextarea">
            <area>15,5,100%-170,30</area>
            <font>title</font>
            <cutdown>no</cutdown>
            <scroll direction="horizontal" startdelay="0" returndelay="0"/>
        </textarea>

        <!-- shows the name of the folder or image -->
        <textarea name="caption" from="basetextarea">
            <area>15,30,100%-100,30</area>
            <font>title</font>
            <cutdown>no</cutdown>
            <scroll direction="horizontal" startdelay="0" returndelay="0"/>
        </textarea>

        <!-- shows current position in grid eg '1/123' -->
        <textarea name="position" from="basetextarea">
            <area>100%-170,5,155,30</area>
            <font>title</font>
            <align>right</align>
        </textarea>

        <!-- Mandatory: the image list 10 columns x 6 rows -->
        <buttonlist name="images0">
            <area>10,30,100%-10,100%-30</area>
            <buttonarea>0,25,100%,100%</buttonarea>
            <wrapstyle>flowing</wrapstyle>
            <layout>grid</layout>
            <arrange>fixed</arrange>
            <align>allcenter</align>
            <spacing>0</spacing>  <!-- (100% - 10*10%) / (10-1) or 0% -->
            <statetype name="buttonitem">
                <area>0,0,100%,100%</area>
                <state name="active" from="galleryactivebutton">
                    <area>0,0,10%,16%</area>
                </state>
                <state name="selectedactive" from="galleryselectedbutton">
                    <area>0,0,10%,16%</area>
                </state>
                <state name="inactive" from="active"/>
                <state name="selectedinactive" from="active"/>
            </statetype>
            <statetype name="upscrollarrow">
                <position>100%-70,5</position>
                <state type="off">
                    <imagetype name="upon">
                        <filename>lb-uparrow-reg.png</filename>
                    </imagetype>
                </state>
                <state type="full">
                    <imagetype name="upoff">
                        <filename>lb-uparrow-sel.png</filename>
                    </imagetype>
                </state>
            </statetype>

            <!-- Show the arrow image that indicates that there are
                more images below -->
            <statetype name="downscrollarrow">
                <position>100%-30,5</position>
                <state type="off">
                    <imagetype name="dnon">
                        <filename>lb-dnarrow-reg.png</filename>
                    </imagetype>
                </state>
                <state type="full">
                    <imagetype name="dnoff">
                        <filename>lb-dnarrow-sel.png</filename>
                    </imagetype>
                </state>
            </statetype>

        </buttonlist>

        <!-- the image list 8 columns x 4 rows -->
        <buttonlist name="images1" from="images0">
            <spacing>7</spacing>  <!-- (100% - 8*12%) / (8-1) or 0.57% -->
            <statetype name="buttonitem">
                <state name="active" from="galleryactivebutton">
                    <area>0,0,12%,24%</area>
                </state>
                <state name="selectedactive" from="galleryselectedbutton">
                    <area>0,0,12%,24%</area>
                </state>
            </statetype>
        </buttonlist>

        <!-- the image list 6 columns x 3 rows -->
        <buttonlist name="images2" from="images0">
            <spacing>10</spacing>  <!-- (100% - 6*16%) / (6-1) or 0.8% -->
            <statetype name="buttonitem">
                <state name="active" from="galleryactivebutton">
                    <area>0,0,16%,32%</area>
                </state>
                <state name="selectedactive" from="galleryselectedbutton">
                    <area>0,0,16%,32%</area>
                </state>
            </statetype>
        </buttonlist>

        <!-- the image list 4 columns x 2 rows -->
        <buttonlist name="images3" from="images0">
            <spacing>0</spacing>  <!-- (100% - 4*25%) / (4-1) or 0% -->
            <statetype name="buttonitem">
                <state name="active" from="galleryactivebutton">
                    <area>0,0,25%,50%</area>
                </state>
                <state name="selectedactive" from="galleryselectedbutton">
                    <area>0,0,25%,50%</area>
                </state>
            </statetype>
        </buttonlist>

        <!-- shows a message when no images are available
             in the current directory -->
         <textarea name="noimages" from="basetextarea">
             <area>0,0,100%,100%</area>
             <align>allcenter</align>
             <multiline>yes</multiline>
         </textarea>

      <!-- Mandatory: Shows file info overlay -->
        <buttonlist name="infolist" from="galleryinfolist">
            <drawfrombottom>true</drawfrombottom>
        </buttonlist>

        <!--Shows scan progress-->
        <group name="progress">
            <area>0,0,100%,100%</area>
            <animation trigger="AboutToShow">
                <section duration="2000">
                    <alpha start="0" end="255" easingcurve="OutQuad"/>
                </section>
            </animation>
            <animation trigger="AboutToHide">
                <section duration="2000">
                    <alpha start="255" end="0" easingcurve="InQuad"/>
                </section>
            </animation>
            <!-- Progress bar-->
            <progressbar name="scanprogressbar" from="baseprogressbar">
                <area>20%,100%-28,75%,28</area>
                <imagetype name="background">
                    <area>0,0,100%,100%</area>
                </imagetype>
                <imagetype name="progressimage">
                    <area>0,0,100%,100%</area>
                </imagetype>
            </progressbar>
            <!--Shows numerical scan progress-->
            <textarea name="scanprogresstext" from="basetextarea">
                <area>20%,100%-29,75%,30</area>
                <align>center</align>
            </textarea>
        </group>

        <!-- shows state of type filter -->
        <textarea name="typefilter" from="basetextarea">
            <area>15,100%-29,180,30</area>
            <align>vcenter</align>
        </textarea>

        <!-- shows state of hidden filter -->
        <textarea name="hidefilter" from="basetextarea">
            <area>100%-180,100%-29,165,30</area>
            <align>vcenter,right</align>
        </textarea>

    </window>

    <!-- Gallery Slideshow window which shows the a single image only or a slideshow. -->
    <window name="slideshow">

        <!-- Extra small text for Gallery images -->
        <fontdef name="gallerytext" from="basesmall">
            <outlinecolor>#000000</outlinecolor>
            <outlinesize>2</outlinesize>
        </fontdef>

        <!-- the background behind the images -->
        <shape name="background_shape">
            <area>0,0,100%,100%</area>
            <fill color="#000000" alpha="255"/>
        </shape>

        <!-- an image  -->
        <imagetype name="image">
            <area>0,0,100%,100%</area>
            <preserveaspect>yes</preserveaspect>
        </imagetype>

        <!-- Represents "Show Captions" state for use as a dependancy by other widgets
         Set = Hide; empty = Show  -->
        <textarea name="hidecaptions" from="basetextarea">
            <area>0,0,0,0</area>
        </textarea>

        <!-- End/Loading/Failed to load status -->
        <textarea name="status" from="basetextarea" depends="!hidecaptions">
            <area>10,0,100%-200,30</area>
            <font>gallerytext</font>
        </textarea>

        <!-- Slide count -->
        <textarea name="slidecount" from="basetextarea" depends="!hidecaptions">
            <area>100%-200,0,190,30</area>
            <font>gallerytext</font>
            <align>right, vcentre</align>
        </textarea>

        <!-- Date/Comment -->
        <textarea name="caption" from="basetextarea" depends="!hidecaptions">
            <area>10,100%-28,100%-20,30</area>
            <font>gallerytext</font>
            <align>centre, vcentre</align>
            <cutdown>no</cutdown>
            <scroll direction="horizontal"/>
        </textarea>

      <!-- Shows file info overlay -->
        <buttonlist name="infolist" from="galleryinfolist"/>

    </window>

</mythuitheme>
